name: CMake

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: "0 12 1,15 * *"

env:
  BUILD_TYPE: Release
  GP2040_BOARDCONFIG: IntegratedPicoFightingBoard
  GP2040_REPO: OpenStickCommunity/GP2040-CE

jobs:
  get-release-version:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - run: |  
        TAG=$(gh release view --repo '${{ env.GP2040_REPO }}' --json tagName --jq .tagName || echo)
        echo 'GP2040_CE_TAG='$TAG >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
    - run: |
        TAG=$(gh release view --repo '${{ github.repository }}' --json tagName --jq .tagName || echo)
        echo 'CURRENT_TAG='$TAG >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
    - run: touch ${{github.workspace}}/release_version.txt
    - if: ${{ env.GP2040_CE_TAG != 'release not found' && env.GP2040_CE_TAG != env.CURRENT_TAG }}
      run: echo $GP2040_CE_TAG > ${{github.workspace}}/release_version.txt
    - uses: actions/upload-artifact@v4.3.1
      with:
        name: Release Version
        path: ${{github.workspace}}/release_version.txt
        if-no-files-found: error

  build-web-interface:
    uses: ./.github/workflows/node.js.yml

  build-firmware:
    needs: build-web-interface
    # The CMake configure and build commands are platform-agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    #Global Setup
    - name: Checkout GP2040-CE
      uses: actions/checkout@v4.1.1
      with:
        repository: '${{ env.GP2040_REPO }}'
        fetch-depth: 0
        fetch-tags: true

    - name: Checkout IPFB
      uses: actions/checkout@v4.1.1
      with:
        path: configs/${{ env.GP2040_BOARDCONFIG }}/

    - name: Setup SDK pipeline
      uses: Fortinbra/RaspberryPiPicoBuild@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.2
      with:
        name: fsData
        path: ${{github.workspace}}/lib/httpd/

    - name: Get core count
      id: core_count
      run : cat /proc/cpuinfo  | grep processor | wc -l
      #End Global Setup

    - name: Pico Build Configure CMake
      shell: bash
      run: PICO_SDK_PATH=${{github.workspace}}/pico-sdk GP2040_BOARDCONFIG=${{ env.GP2040_BOARDCONFIG }} SKIP_WEBBUILD=TRUE cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Pico Build
      shell: bash
      run: GP2040_BOARDCONFIG=${{ env.GP2040_BOARDCONFIG }} cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel ${{steps.core_count.outputs.output}}

    - name: Upload Pico Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: GP2040-CE - ${{ env.GP2040_BOARDCONFIG }}
        path: ${{github.workspace}}/build/GP2040-CE_*_${{ env.GP2040_BOARDCONFIG }}.uf2
        if-no-files-found: error

  create-release:
    permissions:
      contents: write
    needs:
      - get-release-version
      - build-firmware
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Version
        uses: actions/download-artifact@v4.1.2
        with:
          name: Release Version
          path: ${{github.workspace}}/

      - run: echo "RELEASE_VERSION=$(cat release_version.txt)" >> $GITHUB_ENV

      - name: Download Build Artifacts
        if: ${{ env.RELEASE_VERSION != '' }}
        uses: actions/download-artifact@v4.1.2
        with:
          name: GP2040-CE - ${{ env.GP2040_BOARDCONFIG }}
          path: ${{github.workspace}}/

      - name: Create Release
        if: ${{ env.RELEASE_VERSION != '' }}
        run: gh release create --repo '${{ github.repository }}' $(cat env.RELEASE_VERSION) ./*.uf2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
